name: "fashion_model"
platform: "pytorch_libtorch"
max_batch_size: 32

input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [ 3, 160, 160 ]
  }
]

output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [ 5 ]
  },
  {
    name: "OUTPUT__1"
    data_type: TYPE_FP32
    dims: [ 29 ]
  },
  {
    name: "OUTPUT__2"
    data_type: TYPE_FP32
    dims: [ 6 ]
  },
  {
    name: "OUTPUT__3"
    data_type: TYPE_FP32
    dims: [ 39 ]
  }
]

dynamic_batching {
  preferred_batch_size: [ 4, 8, 16, 32 ]
  max_queue_delay_microseconds: 100
}

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]